<project name="POE_Part1" default="run" basedir=".">

    <property name="src.dir" value="src"/>
    <property name="build.dir" value="build"/>
    <property name="main.class" value="poe_part1.POE_Part1"/>

    <target name="init">
        <mkdir dir="${build.dir}"/>
    </target>

    <target name="compile" depends="init">
        <javac srcdir="${src.dir}" destdir="${build.dir}" includeantruntime="false">
            <classpath>
                <fileset dir="lib" includes="**/*.jar"/>
            </classpath>
        </javac>
    </target>

    <target name="run" depends="compile">
        <java fork="true" classname="${main.class}">
            <classpath>
                <pathelement path="${build.dir}"/>
                <fileset dir="lib" includes="**/*.jar"/>
            </classpath>
        </java>
    </target>

    <target name="clean">
        <delete dir="${build.dir}"/>
    </target>

</project>
