<!-- build.xml example -->
<project name="POE_Part1" default="compile" basedir=".">
    <!-- Define properties for directories -->
    <property name="src.dir" location="poe_part1"/> <!-- Your Java source is in poe_part1 directory -->
    <property name="build.dir" location="build"/>
    <property name="lib.dir" location="lib"/>

    <!-- Define the classpath including the JSON JAR -->
    <path id="classpath">
        <fileset dir="${lib.dir}" includes="*.jar"/>
    </path>

    <!-- Target to initialize build directories -->
    <target name="init">
        <mkdir dir="${build.dir}"/>
    </target>

    <!-- Target to compile the Java code -->
    <target name="compile" depends="init" description="Compile the Java source code">
        <javac srcdir="${src.dir}"
               destdir="${build.dir}"
               classpathref="classpath"
               includeantruntime="false" /> <!-- includeantruntime=false avoids Ant's own JARs on classpath -->
    </target>

    <!-- Target to clean compiled files -->
    <target name="clean" description="Clean up compiled classes">
        <delete dir="${build.dir}"/>
    </target>

    <!-- Target to run the application (optional, requires a display) -->
    <target name="run" depends="compile" description="Run the compiled application">
        <java classname="poe_part1.POE_Part1" classpathref="classpath" fork="true">
            <classpath>
                <path location="${build.dir}"/>
            </classpath>
        </java>
    </target>
</project>
