name: Java CI with Ant

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Ant
        run: sudo apt-get update && sudo apt-get install -y ant

      - name: Create lib directory
        run: mkdir -p lib

      - name: Download json.jar
        run: |
          curl -L -o lib/json-20240303.jar https://repo1.maven.org/maven2/org/json/json/20240303/json-20240303.jar

      - name: Compile project with Ant
        run: ant compile

      - name: Run program
        run: ant run
